services:
  db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_DB: proyecto
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  postgres-data:
